export const productsData = {
  fruitsvegetables: [
    {
      id: 1,
      name: "Apple",
      weight: "500 g",
      price: 87,
      oldPrice: 116,
      discount: "25%",
      image: "/media/apple.jpg",
    },
    {
      id: 2,
      name: "Potato",
      weight: "1 kg",
      price: 24,
      oldPrice: 60,
      discount: "25%",
      image: "/media/potato.jpg",
    },
    {
      id: 3,
      name: "Mango",
      weight: "500 g",
      price: 160,
      oldPrice: 220,
      discount: "15%",
      image: "/media/raw-mango.png",
    },
    {
      id: 4,
      name: "Tomato",
      weight: "500 g",
      price: 200,
      oldPrice: 3,
      discount: "20%",
      image: "/media/tomato.jpg",
    },
    {
      id: 5,
      name: "Orange",
      weight: "1 kg",
      price: 200,
      oldPrice: 3,
      discount: "20%",
      image: "/media/orange.jpg",
    },
    {
      id: 6,
      name: "Cauliflower",
      weight: "1 piece",
      price: 30,
      oldPrice: 50,
      discount: "20%",
      image: "/media/cauliflower.jpg",
    },
    {
      id: 7,
      name: "Dragon Fruits",
      weight: "500 g",
      price: 120,
      oldPrice: 300,
      discount: "20%",
      image: "/media/dragon-fruits.jpg",
    },
    {
      id: 8,
      name: "Green Peas",
      weight: "250 g",
      price: 100,
      oldPrice: 150,
      discount: "20%",
      image: "/media/peas.jpg",
    },
    {
      id: 9,
      name: "Melon",
      weight: "1 piece",
      price: 60,
      oldPrice: 120,
      discount: "20%",
      image: "/media/melon.jpg",
    },
    {
      id: 10,
      name: "Lady Finger",
      weight: "500 g",
      price: 40,
      oldPrice: 80,
      discount: "20%",
      image: "/media/ladyfinger.jpg",
    },
    {
      id: 11,
      name: "Watermelon",
      weight: "1 piece",
      price: 70,
      oldPrice: 100,
      discount: "20%",
      image: "/media/watermelon.jpg",
    },
    {
      id: 12,
      name: "Onion",
      weight: "1 kg",
      price: 40,
      oldPrice: 70,
      discount: "20%",
      image: "/media/onion.png",
    },
    {
      id: 13,
      name: "Radish",
      weight: "1 kg",
      price: 70,
      oldPrice: 120,
      discount: "20%",
      image: "/media/radish.jpg",
    },
    {
      id: 14,
      name: "Strawberry",
      weight: "250 g",
      price: 150,
      oldPrice: 300,
      discount: "20%",
      image: "/media/strawberry.jpg",
    },
    {
      id: 15,
      name: "Pineapple",
      weight: "1 piece",
      price: 60,
      oldPrice: 150,
      discount: "20%",
      image: "/media/pineapple.jpg",
    },
    {
      id: 16,
      name: "Spinach",
      weight: "1 pack",
      price: 30,
      oldPrice: 50,
      discount: "20%",
      image: "/media/spinach.jpg",
    },
    {
      id: 17,
      name: "Carrot",
      weight: "1 kg",
      price: 80,
      oldPrice: 100,
      discount: "20%",
      image: "/media/carrot.jpg",
    },
    {
      id: 18,
      name: "Chilli",
      weight: "250 g",
      price: 20,
      oldPrice: 40,
      discount: "20%",
      image: "/media/chilli.jpg",
    },
    {
      id: 19,
      name: "Banana",
      weight: "1 dozen",
      price: 40,
      oldPrice: 80,
      discount: "20%",
      image: "/media/banana.png",
    },
    {
      id: 20,
      name: "Grapes",
      weight: "2 kg",
      price: 190,
      oldPrice: 300,
      discount: "20%",
      image: "/media/grapes.jpg",
    },
  ],

  grains: [
    {
      id: 21,
      name: "Wheat Floor",
      weight: "Fresh Red Apple",
      price: 120,
      oldPrice: 4,
      discount: "20%",
      image: "/media/wheatfloor.jpg",
    },
    {
      id: 22,
      name: "Urad Dal",
      weight: "Organic Bananas",
      price: 60,
      oldPrice: 5,
      discount: "20%",
      image: "/media/uradal.jpg",
    },
    {
      id: 23,
      name: "Chana Dal",
      weight: "Sweet Mango",
      price: 200,
      oldPrice: 3,
      discount: "20%",
      image: "/media/chanadal.jpg",
    },
    {
      id: 24,
      name: "Peanut",
      weight: "Sweet Mango",
      price: 200,
      oldPrice: 3,
      discount: "20%",
      image: "/media/peanut.jpg",
    },
    {
      id: 25,
      name: "Jowar Atta",
      weight: "Sweet Mango",
      price: 200,
      oldPrice: 3,
      discount: "20%",
      image: "/media/jowaratta.jpg",
    },
    {
      id: 26,
      name: "Sunflower Oil",
      weight: "Sweet Mango",
      price: 200,
      oldPrice: 3,
      discount: "20%",
      image: "/media/sunfloweroil.jpg",
    },
    {
      id: 27,
      name: "Mustard Oil",
      weight: "Sweet Mango",
      price: 200,
      oldPrice: 3,
      discount: "20%",
      image: "/media/mustardoil.jpg",
    },
    {
      id: 28,
      name: "Garam Masala",
      weight: "Sweet Mango",
      price: 200,
      oldPrice: 3,
      discount: "20%",
      image: "/media/garamasala.jpg",
    },
    {
      id: 29,
      name: "Chilli Powder",
      weight: "Sweet Mango",
      price: 200,
      oldPrice: 3,
      discount: "20%",
      image: "/media/chillipowder.jpg",
    },
    {
      id: 30,
      name: "Ginger Powder",
      weight: "Sweet Mango",
      price: 200,
      oldPrice: 3,
      discount: "20%",
      image: "/media/gingerpowder.jpg",
    },
  ],
  bakery: [
    {
      id: 31,
      name: "Wheat Bread",
      weight: "400 g",
      price: 55,
      image: "/media/wheatbread.jpg",
    },
    {
      id: 32,
      name: "Zero Maida Whole Wheat",
      weight: "330 g",
      price: 144,
      oldPrice: 159,
      discount: "9%",
      image: "/media/wholebread.jpg",
    },
    {
      id: 33,
      name: "Bonn Pav Bread",
      weight: "250 g",
      price: 38,
      oldPrice: 40,
      discount: "5%",
      image: "/media/pavbread.jpg",
    },
    {
      id: 34,
      name: "Zero Maida Multigrain Bread",
      weight: "250 g",
      price: 68,
      oldPrice: 70,
      discount: "5%",
      image: "/media/MultigrainBread.jpg",
    },
    {
      id: 35,
      name: "Sourdough Focaccia",
      weight: "160 g",
      price: 75,
      oldPrice: 150,
      discount: "15%",
      image: "/media/SourdoughFocaccia.jpg",
    },
    {
      id: 36,
      name: "Walnut Slice Cake",
      weight: "60 g",
      price: 85,
      oldPrice: 100,
      discount: "15%",
      image: "/media/WalnutSliceCake.jpg",
    },
    {
      id: 37,
      name: "Sugar Free Eggless Vanilla Cake",
      weight: "150 g",
      price: 190,
      oldPrice: 199,
      discount: "5%",
      image: "/media/EgglessVanillaCake.jpg",
    },
    {
      id: 38,
      name: "Vanilla Pound Cake",
      weight: "140 g",
      price: 63,
      oldPrice: 75,
      discount: "16%",
      image: "/media/PoundCake.jpg",
    },
  ],
  beverages: [
    {
      id: 39,
      name: "Cola",
      weight: "Whole Wheat Bread",
      price: 50,
      oldPrice: 4,
      discount: "20%",
      image: "/media/bread.jpg",
    },
    {
      id: 40,
      name: "Pepsi",
      weight: "Chocolate Cake",
      price: 350,
      oldPrice: 5,
      discount: "20%",
      image: "/media/cake.jpg",
    },
  ],
  snacksfood: [
    {
      id: 41,
      name: "Potato Chips",
      weight: "Whole Wheat Bread",
      price: 50,
      oldPrice: 4,
      discount: "20%",
      image: "/media/bread.jpg",
    },
    {
      id: 42,
      name: "Kurkure",
      weight: "Chocolate Cake",
      price: 350,
      oldPrice: 5,
      discount: "20%",
      image: "/media/cake.jpg",
    },
  ],
  beautyhygiene: [
    {
      id: 43,
      name: "Lips",
      weight: "Whole Wheat Bread",
      price: 50,
      oldPrice: 4,
      discount: "20%",
      image: "/media/bread.jpg",
    },
    {
      id: 44,
      name: "Face Powder",
      weight: "Chocolate Cake",
      price: 350,
      oldPrice: 5,
      discount: "20%",
      image: "/media/cake.jpg",
    },
  ],
  cleaninghousehold: [
    {
      id: 45,
      name: "floor",
      weight: "Whole Wheat Bread",
      price: 50,
      oldPrice: 4,
      discount: "20%",
      image: "/media/bread.jpg",
    },
    {
      id: 46,
      name: "mirror",
      weight: "Chocolate Cake",
      price: 350,
      oldPrice: 5,
      discount: "20%",
      image: "/media/cake.jpg",
    },
  ],
  eggmeatfish: [
    {
      id: 47,
      name: "White Egg",
      weight: "30 pieces",
      price: 237,
      oldPrice: 350,
      discount: "31%",
      image: "/media/whiteegg.jpg",
    },
    {
      id: 48,
      name: "Desi Egg",
      weight: "10 pieces",
      price: 132,
      oldPrice: 190,
      discount: "30%",
      image: "/media/desiegg.jpg",
    },
    {
      id: 49,
      name: "Chicken Curry Cut",
      weight: "200 g",
      price: 141,
      oldPrice: 250,
      discount: "32%",
      image: "/media/chickenleg.jpg",
    },
    {
      id: 50,
      name: "Chicken Wings",
      weight: "500 g",
      price: 230,
      image: "/media/chickenwings.jpg",
    },
    {
      id: 51,
      name: "Boneless Chicken Breast",
      weight: "450 g",
      price: 240,
      oldPrice: 280,
      discount: "14%",
      image: "/media/chickenboneless.jpg",
    },
    {
      id: 52,
      name: "Chicken Lollipop",
      weight: "450 g",
      price: 240,
      oldPrice: 280,
      discount: "14%",
      image: "/media/desiegg.jpg",
    },
  ],
};
